In [2]:
import numpy as np
print(np.__version__)

1.18.1


l1=[1,2,3,4,5]
type(l1)

In [70]:
print(type(l1))

<class 'list'>


In [17]:
l1=[1,2,3,4,5,6,7,8]
print(type(l1))

<class 'list'>


In [18]:
l2=list(map(lambda x:x*x, l1))

In [19]:
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64]


In [20]:
x=np.array(l2)

In [21]:
print(x)

[ 1  4  9 16 25 36 49 64]


In [22]:
print(type(x))

<class 'numpy.ndarray'>


In [23]:
print(x.shape)

(8,)


In [24]:
print(x.ndim)

1


In [30]:
x=x.reshape(4,2)
print (x)

[[ 1  4]
 [ 9 16]
 [25 36]
 [49 64]]


In [31]:
print(x.ndim)

2


In [37]:
y=np.arange(10,dtype=float)

In [39]:
print(y)
print(y.ndim)
print(y.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
1
float64


In [40]:
a=np.arange(5)
b=np.arange(5)
print(a,b)

[0 1 2 3 4] [0 1 2 3 4]


In [41]:
print(a+b)

[0 2 4 6 8]


In [42]:
print(a-b)

[0 0 0 0 0]


In [43]:
print(np.sin(b))
print(np.cos(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [44]:
print(a>b)

[False False False False False]


In [77]:
import pandas as pd
name=['color','color_name','hex','R','B','G']
df=pd.read_csv('C:/Users/SATYAJIT/Desktop/colors/colors.csv',names=name)

In [78]:
print(df)

                    color             color_name      hex    R    B    G
0      air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1     air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2    air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3         alabama_crimson        Alabama Crimson  #a32638  163   38   56
4              alice_blue             Alice Blue  #f0f8ff  240  248  255
..                    ...                    ...      ...  ...  ...  ...
860         yellow_orange          Yellow Orange  #ffae42  255  174   66
861        yellow_process       Yellow (Process)  #ffef00  255  239    0
862            yellow_ryb           Yellow (Ryb)  #fefe33  254  254   51
863                zaffre                 Zaffre  #0014a8    0   20  168
864     zinnwaldite_brown      Zinnwaldite Brown  #2c1608   44   22    8

[865 rows x 6 columns]


In [79]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [80]:
print(df.describe())

                R           B           G
count  865.000000  865.000000  865.000000
mean   158.598844  124.683237  119.087861
std     85.338432   76.270225   78.343862
min      0.000000    0.000000    0.000000
25%    101.000000   64.000000   53.000000
50%    178.000000  123.000000  119.000000
75%    236.000000  190.000000  186.000000
max    255.000000  255.000000  255.000000


In [81]:
print(df.ndim)

2


In [82]:
print(df.shape)

(865, 6)


In [83]:
print(df.columns)

Index(['color', 'color_name', 'hex', 'R', 'B', 'G'], dtype='object')


In [84]:
print(df.index)

RangeIndex(start=0, stop=865, step=1)


In [85]:
df.dtypes

color         object
color_name    object
hex           object
R              int64
B              int64
G              int64
dtype: object

In [86]:
df.head(15)

color             color_name      hex    R    B    G
0     air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1    air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2   air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3        alabama_crimson        Alabama Crimson  #a32638  163   38   56
4             alice_blue             Alice Blue  #f0f8ff  240  248  255
5       alizarin_crimson       Alizarin Crimson  #e32636  227   38   54
6           alloy_orange           Alloy Orange  #c46210  196   98   16
7                 almond                 Almond  #efdecd  239  222  205
8               amaranth               Amaranth  #e52b50  229   43   80
9                  amber                  Amber  #ffbf00  255  191    0
10         amber_sae_ece        Amber (Sae/Ece)  #ff7e00  255  126    0
11         american_rose          American Rose  #ff033e  255    3   62
12              amethyst               Amethyst     #96c  153  102  204
13         android_green          Android Green  #a4c639  164  198   57
14      anti_flash_white       Anti-Flash White  #f2f3f4  242  243  244

In [87]:
df.tail()

color         color_name      hex    R    B    G
860      yellow_orange      Yellow Orange  #ffae42  255  174   66
861     yellow_process   Yellow (Process)  #ffef00  255  239    0
862         yellow_ryb       Yellow (Ryb)  #fefe33  254  254   51
863             zaffre             Zaffre  #0014a8    0   20  168
864  zinnwaldite_brown  Zinnwaldite Brown  #2c1608   44   22    8

In [88]:
df.sample()

color color_name      hex    R    B    G
7  almond     Almond  #efdecd  239  222  205

In [89]:
df.iloc[10]

color           amber_sae_ece
color_name    Amber (Sae/Ece)
hex                   #ff7e00
R                         255
B                         126
G                           0
Name: 10, dtype: object

In [90]:
df.iloc[0:5]

color             color_name      hex    R    B    G
0    air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1   air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2  air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3       alabama_crimson        Alabama Crimson  #a32638  163   38   56
4            alice_blue             Alice Blue  #f0f8ff  240  248  255

In [92]:
df['color']

0        air_force_blue_raf
1       air_force_blue_usaf
2      air_superiority_blue
3           alabama_crimson
4                alice_blue
               ...         
860           yellow_orange
861          yellow_process
862              yellow_ryb
863                  zaffre
864       zinnwaldite_brown
Name: color, Length: 865, dtype: object

In [93]:
df.iloc[10:15,0:5]

color        color_name      hex    R    B
10     amber_sae_ece   Amber (Sae/Ece)  #ff7e00  255  126
11     american_rose     American Rose  #ff033e  255    3
12          amethyst          Amethyst     #96c  153  102
13     android_green     Android Green  #a4c639  164  198
14  anti_flash_white  Anti-Flash White  #f2f3f4  242  243

In [94]:
df.loc[0:5,'color_name']

0     Air Force Blue (Raf)
1    Air Force Blue (Usaf)
2     Air Superiority Blue
3          Alabama Crimson
4               Alice Blue
5         Alizarin Crimson
Name: color_name, dtype: object

In [95]:
df.loc[0:5,['color_name','hex']]

color_name      hex
0   Air Force Blue (Raf)  #5d8aa8
1  Air Force Blue (Usaf)  #00308f
2   Air Superiority Blue  #72a0c1
3        Alabama Crimson  #a32638
4             Alice Blue  #f0f8ff
5       Alizarin Crimson  #e32636

In [96]:
df['color_name'].unique()

array(['Air Force Blue (Raf)', 'Air Force Blue (Usaf)',
       'Air Superiority Blue', 'Alabama Crimson', 'Alice Blue',
       'Alizarin Crimson', 'Alloy Orange', 'Almond', 'Amaranth', 'Amber',
       'Amber (Sae/Ece)', 'American Rose', 'Amethyst', 'Android Green',
       'Anti-Flash White', 'Antique Brass', 'Antique Fuchsia',
       'Antique Ruby', 'Antique White', 'Ao (English)', 'Apple Green',
       'Apricot', 'Aqua', 'Aquamarine', 'Army Green', 'Arsenic',
       'Arylide Yellow', 'Ash Grey', 'Asparagus', 'Atomic Tangerine',
       'Auburn', 'Aureolin', 'Aurometalsaurus', 'Avocado', 'Azure',
       'Azure Mist/Web', 'Baby Blue', 'Baby Blue Eyes', 'Baby Pink',
       'Ball Blue', 'Banana Mania', 'Banana Yellow', 'Barn Red',
       'Battleship Grey', 'Bazaar', 'Beau Blue', 'Beaver', 'Beige',
       'Big Dip O’Ruby', 'Bisque', 'Bistre', 'Bittersweet',
       'Bittersweet Shimmer', 'Black', 'Black Bean',
       'Black Leather Jacket', 'Black Olive', 'Blanched Almond',
       'Blast-Off

In [97]:
df['color'].value_counts()

maya_blue             1
dark_spring_green     1
spring_green          1
violet_color_wheel    1
olivine               1
                     ..
topaz                 1
amaranth              1
baby_blue             1
azure                 1
rose                  1
Name: color, Length: 865, dtype: int64

In [99]:
df['color'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
860    False
861    False
862    False
863    False
864    False
Name: color, Length: 865, dtype: bool

In [110]:
filter=df['color'].isnull()
df[filter]

Empty DataFrame
Columns: [color, color_name, hex, R, B, G]
Index: []

In [101]:
df2=df.fillna(100)

In [102]:
print(df2)

                    color             color_name      hex    R    B    G
0      air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1     air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2    air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3         alabama_crimson        Alabama Crimson  #a32638  163   38   56
4              alice_blue             Alice Blue  #f0f8ff  240  248  255
..                    ...                    ...      ...  ...  ...  ...
860         yellow_orange          Yellow Orange  #ffae42  255  174   66
861        yellow_process       Yellow (Process)  #ffef00  255  239    0
862            yellow_ryb           Yellow (Ryb)  #fefe33  254  254   51
863                zaffre                 Zaffre  #0014a8    0   20  168
864     zinnwaldite_brown      Zinnwaldite Brown  #2c1608   44   22    8

[865 rows x 6 columns]


In [103]:
df.mean()

R    158.598844
B    124.683237
G    119.087861
dtype: float64

In [104]:
df3=df.fillna(df.mean())

In [105]:
print(df3)

                    color             color_name      hex    R    B    G
0      air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1     air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2    air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3         alabama_crimson        Alabama Crimson  #a32638  163   38   56
4              alice_blue             Alice Blue  #f0f8ff  240  248  255
..                    ...                    ...      ...  ...  ...  ...
860         yellow_orange          Yellow Orange  #ffae42  255  174   66
861        yellow_process       Yellow (Process)  #ffef00  255  239    0
862            yellow_ryb           Yellow (Ryb)  #fefe33  254  254   51
863                zaffre                 Zaffre  #0014a8    0   20  168
864     zinnwaldite_brown      Zinnwaldite Brown  #2c1608   44   22    8

[865 rows x 6 columns]


In [106]:
df4=df.dropna()

In [107]:
print(df4)

                    color             color_name      hex    R    B    G
0      air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1     air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2    air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3         alabama_crimson        Alabama Crimson  #a32638  163   38   56
4              alice_blue             Alice Blue  #f0f8ff  240  248  255
..                    ...                    ...      ...  ...  ...  ...
860         yellow_orange          Yellow Orange  #ffae42  255  174   66
861        yellow_process       Yellow (Process)  #ffef00  255  239    0
862            yellow_ryb           Yellow (Ryb)  #fefe33  254  254   51
863                zaffre                 Zaffre  #0014a8    0   20  168
864     zinnwaldite_brown      Zinnwaldite Brown  #2c1608   44   22    8

[865 rows x 6 columns]
